[package]
name = "__init"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["unstable-locales"] }
hex-literal = "0.4.1"
sha2 = "0.9.8"
use = "0.0.1-pre.0"

serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
